### ISSUE TITLE
Error: Failed to load

### ISSUE THREAD

**Issue by andarolhar** [iam-raihan/crud-app-vuejs-vuetify#3]
Hi, thank you for sharing :)

i am getting this error:

> Failed to load https://hidden-mesa-33270.herokuapp.com/api/name: The 'Access-Control-Allow-Origin' header has a value 'https://crud-demoapp.firebaseapp.com' that is not equal to the supplied origin. Origin 'http://localhost:8080' is therefore not allowed access.
> RandomName.vue?0803:81 Error: Network Error
>     at createError (createError.js?f777:16)
>     at XMLHttpRequest.handleError (xhr.js?14ed:87)
> xhr.js?14ed:178 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://hidden-mesa-33270.herokuapp.com/api/name with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by iam-raihan** [comment]
that was a CORS issue, fixed now.

**Comment by iam-raihan** [comment]
that was a **CORS** issue, fixed now.
